const myths = [
  {
    id: '1',
    slug: 'ragnarok',
    title: 'Ragnarök',
    culture: 'Norse',
    type: 'eschatology',
    wikipediaTitle: 'Ragnarök',
    era: 'Viking Age',
    summary: 'The final battle that ends the world, where gods and giants clash, resulting in the destruction and rebirth of the cosmos.',
    themes: ['end of world', 'rebirth', 'destiny', 'war', 'transformation'],
  },
  {
    id: '2',
    slug: 'pralaya',
    title: 'Pralaya',
    culture: 'Hindu',
    type: 'eschatology',
    wikipediaTitle: 'Pralaya',
    era: 'Ancient',
    summary: 'The periodic dissolution of the universe, when all existence returns to the unmanifest state before creation begins anew.',
    themes: ['cosmic cycles', 'dissolution', 'renewal', 'time', 'Brahman'],
  },
  {
    id: '3',
    slug: 'popol-vuh-cosmogony',
    title: 'Popol Vuh Cosmogony',
    culture: 'Mayan',
    type: 'cosmogony',
    wikipediaTitle: 'Popol Vuh',
    era: 'Classic Period',
    summary: 'The story of how the gods created the world through multiple attempts, leading to the emergence of the Hero Twins.',
    themes: ['creation attempts', 'corn', 'duality', 'heroes', 'world tree'],
  },
  {
    id: '4',
    slug: 'popol-vuh-anthropogony',
    title: 'Popol Vuh Anthropogony',
    culture: 'Mayan',
    type: 'anthropogony',
    wikipediaTitle: 'Popol Vuh',
    era: 'Classic Period',
    summary: 'The gods create humanity through multiple attempts, first from earth, then wood, and finally from corn.',
    themes: ['creation attempts', 'corn', 'humanity', 'trial and error', 'maize'],
  },
  {
    id: '5',
    slug: 'obatala-cosmogony',
    title: 'Obatala Cosmogony',
    culture: 'Yoruba',
    type: 'cosmogony',
    wikipediaTitle: 'Yoruba religion',
    era: 'Pre-colonial',
    summary: 'Obatala descends from the high god Olodumare on a golden chain, carrying a snail shell of sand and a hen. He pours the sand onto the primordial waters and lets the hen scratch it into land, creating the first solid earth of Ile-Ife, the center of Yoruba cosmology.',
    themes: ['orishas', 'cosmic order', 'divine creation', 'foundation', 'Ile-Ife'],
  },
  {
    id: '6',
    slug: 'obatala-anthropogony',
    title: 'Obatala Anthropogony',
    culture: 'Yoruba',
    type: 'anthropogony',
    wikipediaTitle: 'Yoruba religion',
    era: 'Pre-colonial',
    summary: 'In his workshop at Ile-Ife, Obatala shapes the first humans from sacred clay. When he drinks palm wine and works drunk, some figures come out differently, giving rise to human diversity and disability. Olodumare breathes life into all of them, making each body a valid vessel of spirit.',
    themes: ['clay molding', 'orishas', 'life force', 'divine breath', 'human diversity'],
  },
  {
    id: '7',
    slug: 'anubis-underworld',
    title: 'Anubis and the Underworld',
    culture: 'Egyptian',
    type: 'underworld',
    wikipediaTitle: 'Anubis',
    era: 'Ancient',
    summary: 'Anubis, the jackal-headed god, guides souls through Duat, the Egyptian underworld. In the Hall of Two Truths, he weighs each heart against the feather of Ma\'at. Those whose hearts balance are granted eternal life in the Field of Reeds, while the heavy-hearted are devoured by Ammit, the devourer of the dead.',
    themes: ['judgment', 'weighing', 'afterlife', 'justice', 'transformation'],
  },
  {
    id: '8',
    slug: 'izkali',
    title: 'Izkali',
    culture: 'Aztec',
    type: 'eschatology',
    wikipediaTitle: 'Aztec mythology',
    era: 'Post-Classic',
    summary: 'The fifth and final sun will be destroyed by earthquakes, marking the end of the current cosmic age.',
    themes: ['world ages', 'earthquakes', 'cycles', 'quetzalcoatl', 'sacrifice'],
  },
  {
    id: '9',
    slug: 'yomi',
    title: 'Yomi',
    culture: 'Japanese',
    type: 'underworld',
    wikipediaTitle: 'Yomi',
    era: 'Classical',
    summary: 'Yomi, the dark and polluted land of the dead, is ruled by Izanami after she dies giving birth to fire. When Izanagi descends to retrieve her, he finds her transformed and decayed. He flees, and Izanami pursues him, but he blocks the entrance with a boulder, creating the permanent boundary between the living and the dead.',
    themes: ['death', 'boundaries', 'pollution', 'escape', 'separation'],
  },
  {
    id: '10',
    slug: 'birthing-the-world',
    title: 'Birthing the World',
    culture: 'Inuit',
    type: 'cosmogony',
    wikipediaTitle: 'Sedna (mythology)',
    era: 'Pre-colonial',
    summary: 'In the beginning, Sedna, the sea goddess, creates all sea creatures from her fingers. Raven, the trickster, steals the sun, moon, and stars from a wealthy man\'s house and releases them into the sky, bringing light to the dark world. These acts establish the cycles of hunting, fishing, and survival that define Inuit life.',
    themes: ['sea', 'hunting', 'darkness and light', 'cycles', 'animals'],
  },
  {
    id: '11',
    slug: 'mana-anthropogony',
    title: 'Mana and the First Humans',
    culture: 'Polynesian',
    type: 'anthropogony',
    wikipediaTitle: 'Mana (Oceanian mythology)',
    era: 'Pre-colonial',
    summary: 'From the primordial chaos of Po, the first gods emerge through genealogical descent. These divine ancestors then create humanity from their own substance—sometimes from their own bodies, sometimes from earth mixed with divine essence. The life force mana flows through all creation, connecting gods, humans, and the natural world in a sacred web of being.',
    themes: ['chaos', 'genealogy', 'creation from body', 'mana', 'humanity'],
  },
  {
    id: '12',
    slug: 'hel',
    title: 'Hel and the Dead',
    culture: 'Norse',
    type: 'underworld',
    wikipediaTitle: 'Hel (location)',
    era: 'Viking Age',
    summary: 'Hel, the cold and misty realm of the dead, lies beneath one of Yggdrasil\'s roots. Ruled by the goddess Hel, daughter of Loki, it receives those who die of old age or illness—not in battle. The hall is called Éljúðnir, and the dead live there in a shadowy existence, separate from the honored dead in Valhalla.',
    themes: ['afterlife', 'judgment', 'cold', 'mortality', 'fate'],
  },
  {
    id: '13',
    slug: 'kali-yuga',
    title: 'Kali Yuga',
    culture: 'Hindu',
    type: 'eschatology',
    wikipediaTitle: 'Kali Yuga',
    era: 'Classical',
    summary: 'Kali Yuga, the current age of decline, is marked by strife, spiritual darkness, and the breakdown of dharma. Virtue diminishes, truth fades, and humanity drifts from cosmic order. This dark age will end when Kalki, the final avatar of Vishnu, arrives on a white horse to destroy the corrupt and restore righteousness, beginning a new golden age.',
    themes: ['decline', 'ages', 'purification', 'avatar', 'cycles'],
  },
  {
    id: '14',
    slug: 'egyptian-cosmogony',
    title: 'Egyptian Cosmogony',
    culture: 'Egyptian',
    type: 'cosmogony',
    wikipediaTitle: 'Atum',
    era: 'Ancient',
    summary: 'In the beginning, only the primeval waters of Nun exist. From this chaos, Atum emerges on the first mound of earth. Through self-generation, Atum creates Shu (air) and Tefnut (moisture), who then give birth to Geb (earth) and Nut (sky). This divine genealogy establishes the cosmic order and the foundation of the Egyptian world.',
    themes: ['primeval waters', 'self-creation', 'Atum', 'order from chaos', 'Nun'],
  },
  {
    id: '15',
    slug: 'egyptian-anthropogony',
    title: 'Egyptian Anthropogony',
    culture: 'Egyptian',
    type: 'anthropogony',
    wikipediaTitle: 'Khnum',
    era: 'Ancient',
    summary: 'Humans are created in multiple ways across Egyptian tradition. In one version, they emerge from the tears of Ra, shed in a moment of divine emotion. In another, Khnum, the ram-headed god, shapes each person from clay on his potter\'s wheel, carefully crafting body and ka (life force) before breathing the breath of life into them.',
    themes: ['tears of Ra', 'clay molding', 'Khnum', 'potter\'s wheel', 'divine breath'],
  },
  {
    id: '16',
    slug: 'egyptian-eschatology',
    title: 'Egyptian Eschatology',
    culture: 'Egyptian',
    type: 'eschatology',
    wikipediaTitle: 'Apep',
    era: 'Ancient',
    summary: 'Each night, Ra\'s sun boat travels through the underworld, facing the chaos serpent Apophis who seeks to devour it and end the world. The gods, led by Set, battle Apophis nightly, binding and cutting him to pieces. Though he regenerates, the gods\' eternal vigilance ensures the sun rises again, maintaining cosmic order and preventing the final dissolution.',
    themes: ['Apophis', 'sun boat', 'eternal struggle', 'cosmic order', 'Ma\'at'],
  },
  {
    id: '17',
    slug: 'yoruba-underworld',
    title: 'Orun-apaadi',
    culture: 'Yoruba',
    type: 'underworld',
    wikipediaTitle: 'Yoruba religion',
    era: 'Pre-colonial',
    summary: 'Orun-apaadi, the realm of the dead, is where souls of the deceased dwell under the watch of ancestors and orishas. Unlike Orun-rere, the good heaven, this is a place of rest and reflection. The dead maintain connection with the living through ancestor veneration, and can be reincarnated if their destiny is not yet complete.',
    themes: ['ancestors', 'orishas', 'afterlife', 'ancestral realm', 'spiritual journey'],
  },
  {
    id: '18',
    slug: 'norse-cosmogony',
    title: 'Norse Cosmogony',
    culture: 'Norse',
    type: 'cosmogony',
    wikipediaTitle: 'Ymir',
    era: 'Viking Age',
    summary: 'In the void Ginnungagap, the primeval giant Ymir is born from melting ice. When Odin and his brothers slay Ymir, they fashion the world from his body: his flesh becomes the earth, his blood the seas, his bones the mountains, his skull the sky, and his brain the clouds. At the center stands Yggdrasil, the world tree connecting all nine realms.',
    themes: ['Ymir', 'giant\'s body', 'world tree', 'Yggdrasil', 'primeval beings'],
  },
  {
    id: '45',
    slug: 'norse-anthropogony',
    title: 'Ask and Embla',
    culture: 'Norse',
    type: 'anthropogony',
    wikipediaTitle: 'Ask and Embla',
    era: 'Viking Age',
    summary: 'Walking along a beach, the three gods Odin, Hœnir, and Lóðurr (or Vili, Vé, and Odin) find two trees—an ash and an elm. They transform these trees into the first humans: Ask (ash tree, the man) and Embla (the woman). The gods bestow upon them breath of life, movement and intelligence, shape, speech, hearing, and sight. Ask and Embla become the progenitors of all humanity and are given a home within the walls of Midgard, the realm of humans.',
    themes: ['trees', 'first humans', 'divine gifts', 'Midgard', 'progenitors'],
  },
  {
    id: '19',
    slug: 'hindu-cosmogony',
    title: 'Hindu Cosmogony',
    culture: 'Hindu',
    type: 'cosmogony',
    wikipediaTitle: 'Hindu cosmology',
    era: 'Ancient',
    summary: 'The universe exists in endless cycles of creation, maintenance, and dissolution. From the unmanifest Brahman, the cosmic egg emerges, containing all potential. Brahma creates the manifest world, Vishnu maintains it, and Shiva dissolves it back into the unmanifest. Each cycle lasts billions of years, and the process repeats eternally, with each universe a breath of the cosmic being.',
    themes: ['Brahman', 'cosmic cycles', 'emanation', 'manifestation', 'Vedic cosmology'],
  },
  {
    id: '20',
    slug: 'hindu-anthropogony',
    title: 'Hindu Anthropogony',
    culture: 'Hindu',
    type: 'anthropogony',
    wikipediaTitle: 'Manu (Hinduism)',
    era: 'Ancient',
    summary: 'Manu, the first man and progenitor of humanity, is created by Brahma at the beginning of each cosmic age. From Manu, all human lineages descend through the Manvantaras, the great time periods ruled by different Manus. Each Manu presides over a cycle of creation, teaching dharma and establishing the social and cosmic order for his age.',
    themes: ['Manu', 'Brahma', 'first man', 'Manvantaras', 'lineage'],
  },
  {
    id: '21',
    slug: 'hindu-underworld',
    title: 'Naraka',
    culture: 'Hindu',
    type: 'underworld',
    wikipediaTitle: 'Naraka (Hinduism)',
    era: 'Classical',
    summary: 'Naraka is the realm of punishment where souls atone for sins before rebirth. Ruled by Yama, the god of death and justice, it contains many hells, each designed for specific wrongdoings. After serving their sentence, souls are reborn according to their remaining karma, continuing the cycle of samsara.',
    themes: ['punishment', 'Yama', 'rebirth', 'karma', 'atonement'],
  },
  {
    id: '22',
    slug: 'aztec-cosmogony',
    title: 'Aztec Cosmogony',
    culture: 'Aztec',
    type: 'cosmogony',
    wikipediaTitle: 'Five Suns',
    era: 'Post-Classic',
    summary: 'The Aztec world has been created and destroyed four times, each age ruled by a different sun. The first four suns ended in jaguars, wind, fire rain, and flood. The current fifth sun, Tonatiuh, was created when the gods sacrificed themselves at Teotihuacan. This sun requires constant human sacrifice to keep moving across the sky, maintaining the cosmic order.',
    themes: ['five suns', 'cosmic cycles', 'sacrifice', 'Tezcatlipoca', 'Quetzalcoatl'],
  },
  {
    id: '23',
    slug: 'aztec-anthropogony',
    title: 'Aztec Anthropogony',
    culture: 'Aztec',
    type: 'anthropogony',
    wikipediaTitle: 'Quetzalcoatl',
    era: 'Post-Classic',
    summary: 'After the previous four worlds are destroyed, Quetzalcoatl descends to Mictlan to retrieve the bones of the last humans. He breaks them while fleeing the death gods, then grinds them into meal. The gods mix this bone meal with Quetzalcoatl\'s own blood, creating the first humans of the fifth sun. Corn becomes the sacred food that sustains this new humanity.',
    themes: ['Quetzalcoatl', 'bone and blood', 'corn', 'sacrifice', 'previous races'],
  },
  {
    id: '24',
    slug: 'aztec-underworld',
    title: 'Mictlan',
    culture: 'Aztec',
    type: 'underworld',
    wikipediaTitle: 'Mictlantecuhtli',
    era: 'Post-Classic',
    summary: 'Mictlan is the deep underworld of the Aztecs, a cold and misty realm ruled by Mictlantecuhtli and Mictecacíhuatl. Souls of most people travel down through nine treacherous layers—past collapsing mountains, obsidian winds, and a river crossed with the help of a psychopomp dog—before finally reaching the skeletal lord of the dead.',
    themes: ['Mictlantecuhtli', 'nine levels', 'journey', 'trials', 'psychopomp dog'],
  },
  {
    id: '25',
    slug: 'mayan-eschatology',
    title: 'Mayan Eschatology',
    culture: 'Mayan',
    type: 'eschatology',
    wikipediaTitle: 'Maya mythology',
    era: 'Classic Period',
    summary: 'In Mayan eschatology, the current world is only one age in a long sequence of creations and destructions. The world may end in fire, flood, or cosmic upheaval, as the gods clear away a failing creation to make room for a new one.',
    themes: ['fire', 'flood', 'world cycles', 'destruction', 'renewal'],
  },
  {
    id: '26',
    slug: 'mayan-underworld',
    title: 'Xibalba',
    culture: 'Mayan',
    type: 'underworld',
    wikipediaTitle: 'Xibalba',
    era: 'Classic Period',
    summary: 'Xibalba, the "place of fright," is the dark underworld ruled by the death gods Hun-Came and Vucub-Came. The Hero Twins, Hunahpu and Xbalanque, descend to avenge their father, facing deadly trials in dark houses filled with jaguars, knives, cold, fire, and bats. Through trickery and skill, they defeat the lords of death and restore cosmic order.',
    themes: ['death gods', 'Hero Twins', 'trials', 'journey', 'trickery'],
  },
  {
    id: '27',
    slug: 'japanese-cosmogony',
    title: 'Japanese Cosmogony',
    culture: 'Japanese',
    type: 'cosmogony',
    wikipediaTitle: 'Japanese mythology',
    era: 'Classical',
    summary: 'The world created when Izanagi and Izanami stir the primeval ocean with the heavenly jeweled spear, forming the first land.',
    themes: ['Izanagi', 'Izanami', 'jeweled spear', 'primeval ocean', 'first land'],
  },
  {
    id: '28',
    slug: 'japanese-anthropogony',
    title: 'Japanese Anthropogony',
    culture: 'Japanese',
    type: 'anthropogony',
    wikipediaTitle: 'Izanami',
    era: 'Classical',
    summary: 'The first humans are created by Izanagi and Izanami through their union, giving birth to the islands and peoples of Japan.',
    themes: ['Izanagi', 'Izanami', 'birth', 'islands', 'union'],
  },
  {
    id: '29',
    slug: 'inuit-anthropogony',
    title: 'Inuit Anthropogony',
    culture: 'Inuit',
    type: 'anthropogony',
    wikipediaTitle: 'Inuit mythology',
    era: 'Pre-colonial',
    summary: 'The first humans emerge from pods or are created by Raven from clay, establishing the Inuit people.',
    themes: ['Raven', 'clay', 'pods', 'first humans', 'creation'],
  },
  {
    id: '30',
    slug: 'inuit-eschatology',
    title: 'Inuit Eschatology',
    culture: 'Inuit',
    type: 'eschatology',
    wikipediaTitle: 'Inuit mythology',
    era: 'Pre-colonial',
    summary: 'Some Inuit traditions imagine the end coming when the world grows too cold and the great spirits abandon the earth. Hunters can no longer find game, sea ice never breaks, and the balance between humans, animals, and spirits finally collapses.',
    themes: ['cold', 'abandonment', 'spirits', 'decline', 'end times'],
  },
  {
    id: '43',
    slug: 'inuit-underworld',
    title: 'Adlivun',
    culture: 'Inuit',
    type: 'underworld',
    wikipediaTitle: 'Sedna (mythology)',
    era: 'Pre-colonial',
    summary: 'Adlivun is the underworld realm of the Inuit, ruled by Sedna, the sea goddess. Located beneath the sea or in the depths of the earth, it is where the souls of the dead dwell. Sedna, who was transformed into a sea goddess after being cast into the ocean, controls all sea creatures and watches over the dead. Shamans must journey to Adlivun to appease Sedna when she withholds animals from hunters, combing her hair and calming her anger to restore the balance between humans and the spirit world.',
    themes: ['Sedna', 'underworld', 'sea goddess', 'shamans', 'afterlife'],
  },
  {
    id: '31',
    slug: 'greek-cosmogony',
    title: 'Greek Cosmogony',
    culture: 'Greek',
    type: 'cosmogony',
    wikipediaTitle: 'Greek mythology',
    era: 'Classical',
    summary: 'The world emerges from Chaos, with Gaia, Tartarus, and Eros appearing first, followed by the Titans.',
    themes: ['Chaos', 'Gaia', 'Tartarus', 'Eros', 'Titans'],
  },
  {
    id: '32',
    slug: 'greek-anthropogony',
    title: 'Prometheus and Humans',
    culture: 'Greek',
    type: 'anthropogony',
    wikipediaTitle: 'Prometheus',
    era: 'Classical',
    summary: 'Prometheus molds humans from clay, and Athena breathes life into them, creating humanity with divine aid.',
    themes: ['Prometheus', 'clay', 'Athena', 'divine breath', 'humanity'],
  },
  {
    id: '33',
    slug: 'greek-eschatology',
    title: 'Greek Eschatology',
    culture: 'Greek',
    type: 'eschatology',
    wikipediaTitle: 'Greek mythology',
    era: 'Classical',
    summary: 'The end comes when Zeus decides to destroy humanity, as in the flood of Deucalion, or through cosmic upheaval.',
    themes: ['Zeus', 'flood', 'Deucalion', 'destruction', 'judgment'],
  },
  {
    id: '34',
    slug: 'greek-underworld',
    title: 'Hades',
    culture: 'Greek',
    type: 'underworld',
    wikipediaTitle: 'Greek underworld',
    era: 'Classical',
    summary: 'Hades, the realm of the dead, is ruled by the god Hades and his queen Persephone. Souls cross the river Styx with Charon the ferryman, are judged by Minos, Rhadamanthus, and Aeacus, then sent to their fate: Elysium for heroes, the Asphodel Meadows for ordinary souls, or Tartarus for the wicked.',
    themes: ['Hades', 'judgment', 'Elysium', 'Tartarus', 'Asphodel'],
  },
  {
    id: '35',
    slug: 'polynesian-cosmogony',
    title: 'Polynesian Cosmogony',
    culture: 'Polynesian',
    type: 'cosmogony',
    wikipediaTitle: 'Polynesian narrative',
    era: 'Pre-colonial',
    summary: 'From the primordial void Po, the first gods emerge through genealogical descent. Rangi (sky) and Papa (earth) are born locked in embrace, their children trapped between them in darkness. The children, led by Tāne, force them apart: Rangi becomes the sky above, Papa the earth below, and their children become the gods of the natural world. The islands themselves are sometimes said to be pieces of Papa\'s body.',
    themes: ['Po', 'void', 'sky and earth', 'separation', 'islands'],
  },
  {
    id: '36',
    slug: 'polynesian-eschatology',
    title: 'Polynesian Eschatology',
    culture: 'Polynesian',
    type: 'eschatology',
    wikipediaTitle: 'Polynesian narrative',
    era: 'Pre-colonial',
    summary: 'In some Polynesian traditions, the end comes when the gods withdraw their presence and mana from the world. The cosmic order unravels, the separation between sky and earth collapses, and all creation returns to the primordial void Po. This dissolution is not necessarily final—it may be the prelude to a new cycle of creation, as the gods may choose to begin again.',
    themes: ['withdrawal', 'void', 'return', 'gods', 'end times'],
  },
  {
    id: '37',
    slug: 'mesopotamian-cosmogony',
    title: 'Mesopotamian Cosmogony',
    culture: 'Mesopotamian',
    type: 'cosmogony',
    wikipediaTitle: 'Enûma Eliš',
    era: 'Ancient',
    summary: 'In the beginning, only the saltwater Tiamat and freshwater Apsu exist. Their union creates the first gods, who eventually kill Apsu. Enraged, Tiamat creates an army of monsters to destroy them. Marduk, the champion of the younger gods, defeats Tiamat in battle, splits her body in two to form heaven and earth, and establishes cosmic order from her remains.',
    themes: ['Tiamat', 'Marduk', 'battle', 'body', 'Enuma Elish'],
  },
  {
    id: '38',
    slug: 'mesopotamian-anthropogony',
    title: 'Mesopotamian Anthropogony',
    culture: 'Mesopotamian',
    type: 'anthropogony',
    wikipediaTitle: 'Atra-Hasis',
    era: 'Ancient',
    summary: 'When the younger gods grow tired of agricultural labor, they rebel against the older gods. To resolve the conflict, the wise god Ea creates humans from clay mixed with the blood of Kingu, a slain rebel god. This divine essence gives humans intelligence and purpose, but also binds them to serve the gods forever, performing the work the gods no longer wish to do.',
    themes: ['clay', 'divine blood', 'servitude', 'labor', 'creation'],
  },
  {
    id: '39',
    slug: 'mesopotamian-eschatology',
    title: 'Mesopotamian Eschatology',
    culture: 'Mesopotamian',
    type: 'eschatology',
    wikipediaTitle: 'Epic of Gilgamesh',
    era: 'Ancient',
    summary: 'In Mesopotamian tradition, the end may come through divine flood, as when Enlil sends the great deluge to destroy noisy humanity. Only Utnapishtim, warned by Ea, survives in an ark. The gods later regret their decision and grant Utnapishtim immortality. The epic suggests that while individual humans die, humanity itself endures, though always subject to the gods\' capricious will.',
    themes: ['flood', 'divine wrath', 'destruction', 'judgment', 'cosmic'],
  },
  {
    id: '46',
    slug: 'mesopotamian-underworld',
    title: 'Mesopotamian Underworld',
    culture: 'Mesopotamian',
    type: 'underworld',
    wikipediaTitle: 'Ancient Mesopotamian underworld',
    era: 'Ancient',
    summary: 'The Mesopotamian underworld, known as Irkalla or Kur, is a dark and gloomy realm ruled by Ereshkigal, the goddess of death. Located beneath the earth, it is a place where the dead exist in a shadowy state, eating dust and clay. The underworld is guarded by gates and demons, and souls must cross a river to reach it. Unlike some traditions, there is no judgment or reward—all the dead, regardless of their deeds in life, share the same bleak existence in this realm of eternal darkness.',
    themes: ['Irkalla', 'Kur', 'Ereshkigal', 'darkness', 'demons'],
  },
  {
    id: '40',
    slug: 'chinese-cosmogony',
    title: 'Chinese Cosmogony',
    culture: 'Chinese',
    type: 'cosmogony',
    wikipediaTitle: 'Pangu',
    era: 'Classical',
    summary: 'In the beginning, the universe is a chaotic egg containing Pangu. When Pangu awakens, he breaks the egg, separating yin (dark, heavy) and yang (light, rising). He stands between them, pushing them apart for 18,000 years. When he dies, his body transforms: his breath becomes wind and clouds, his voice thunder, his left eye the sun, right eye the moon, his body the mountains, blood the rivers, and his hair the stars.',
    themes: ['Pangu', 'yin and yang', 'chaos', 'separation', 'heaven and earth'],
  },
  {
    id: '41',
    slug: 'chinese-anthropogony',
    title: 'Chinese Anthropogony',
    culture: 'Chinese',
    type: 'anthropogony',
    wikipediaTitle: 'Nüwa',
    era: 'Classical',
    summary: 'After Pangu creates the world, Nuwa, the serpent-bodied goddess, finds it empty and lonely. She takes yellow earth and carefully shapes the first humans by hand, creating them one by one. When this becomes too tedious, she dips a rope in mud and flicks it, creating many people at once. The hand-made humans become the nobles and rulers, while the rope-flicked ones become the common people.',
    themes: ['Nuwa', 'yellow clay', 'rope', 'individual creation', 'mass creation'],
  },
  {
    id: '42',
    slug: 'chinese-eschatology',
    title: 'Chinese Eschatology',
    culture: 'Chinese',
    type: 'eschatology',
    wikipediaTitle: 'Chinese mythology',
    era: 'Classical',
    summary: 'In some strands of Chinese thought, the end of an age comes when cycles of virtue and order decay into corruption, and the Mandate of Heaven is withdrawn. Cosmic patterns unwind, the world returns toward chaos, and only after this collapse can a new, harmonious era emerge.',
    themes: ['cosmic cycles', 'chaos', 'return', 'renewal', 'cycles'],
  },
  {
    id: '44',
    slug: 'chinese-underworld',
    title: 'Diyu',
    culture: 'Chinese',
    type: 'underworld',
    wikipediaTitle: 'Diyu',
    era: 'Classical',
    summary: 'Diyu is the realm of the dead in Chinese mythology, a complex underworld with multiple levels and courts where souls are judged by Yama, the king of hell. The dead face trials based on their deeds in life, and may be punished, purified, or reincarnated. Diyu contains eighteen levels of hell, each designed for specific sins, and souls may pass through these levels before being reborn or reaching paradise.',
    themes: ['Yama', 'judgment', 'eighteen levels', 'punishment', 'reincarnation'],
  },
];

function getMythBySlug(slug) {
  return myths.find(m => m.slug === slug);
}

function getRelatedMyths(currentMyth, limit = 5) {
  return myths
    .filter(m => 
      m.id !== currentMyth.id && 
      (m.culture === currentMyth.culture || m.type === currentMyth.type)
    )
    .slice(0, limit);
}

